version: '3.8'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.prod
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.prod
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
