version: '3.8'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.prod
    ports:
      - "8080:8080"
    depends_on:
      - frontend
    command: >
      sh -c "pipenv run uvicorn main:app --host 0.0.0.0 --port 8080 --reload & \
      /usr/bin/sleep 10 && pipenv run python test_integration.py && fg"

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.prod
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
